/* Every word the page shows lives in this file. Generated by build-content.js from cards.json; do not edit by hand.
   Every card is written for this lead magnet. Nothing is imported from the strategy-doc block library. */
window.SIDES = {
  "ricos": {
    "id": "ricos-tacos",
    "name": "Rico's Tacos, the series",
    "officialChannel": true,
    "video": {
      "id": "PeUsXJ4ccXY",
      "label": "Rico's Tacos, Episode 1: Flavor Has a Price",
      "caption": "Episode 1: Flavor Has a Price &middot; MinivelaTV"
    },
    "scale": "Series · 22 short episodes",
    "title": "A scripted comedy in short episodes",
    "spec": [
      [
        "What it is",
        "A scripted comedy about a taco stand, told in short episodes, made by P&G with Albertsons Media Collective and Minivela."
      ],
      [
        "How often",
        "A new episode about twice a week, from 23 June to 28 August 2026."
      ],
      [
        "Episode length",
        "49 seconds to two minutes 28 seconds. Episode 1 runs 70 seconds."
      ]
    ],
    "stats": [
      [
        "1,305,315",
        "Views Across 22 Episodes, 14 Sep 2026"
      ],
      [
        "200,495",
        "Views, Episode 1"
      ],
      [
        "49,000+",
        "Views On Each Episode From Episode 11 On"
      ]
    ],
    "note": "The series playlist on MinivelaTV, the channel of Minivela, which makes Rico's Tacos with P&G and Albertsons Media Collective. 22 full episodes (two are numbered 16), 23 June to 28 August 2026; views read 14 September 2026. Episodes 9 and 10 show 1,080 and 78 views, far below every other episode, so the per-episode figure starts at episode 11. The two films in this round sit on different channels."
  },
  "tideSpot": {
    "id": "tide-school-lunch",
    "name": "School Lunch, the Tide commercial",
    "officialChannel": true,
    "video": {
      "id": "xPHs8yT8cPM",
      "label": "Tide, School Lunch",
      "caption": "School Lunch &middot; Tide"
    },
    "scale": "Commercial · One film",
    "title": "A thirty-second commercial",
    "spec": [
      [
        "What it is",
        "A commercial for Tide, published as one film."
      ]
    ],
    "stats": [
      [
        "27,157",
        "YouTube Views, 14 Sep 2026"
      ],
      [
        "1",
        "Film"
      ],
      [
        "15 Oct 2025",
        "Published"
      ]
    ],
    "note": "Tide's own channel, published 15 October 2025. Views read 14 September 2026. The two films in this round sit on different channels."
  },
  "mayhem": {
    "id": "mayhem",
    "name": "Mayhem",
    "officialChannel": true,
    "video": {
      "id": "InPoTHIrnp0",
      "label": "Mayhem: Action Hero, an Allstate commercial",
      "caption": "Mayhem: Action Hero &middot; Allstate"
    },
    "scale": "Commercial · The same character since 2010",
    "title": "Mayhem, played by Dean Winters",
    "spec": [
      [
        "What it is",
        "A commercial starring Allstate's character Mayhem."
      ],
      [
        "The cast",
        "The same character, Mayhem, since 2010."
      ]
    ],
    "stats": [
      [
        "#1",
        "Most Memorable Ads, Insurance Mascots"
      ],
      [
        "+8%",
        "Likeability, Above The Norm"
      ],
      [
        "31%",
        "Would Most Like A Beer With Mayhem"
      ]
    ],
    "note": "<a href=\"https://martechedge.com/news/liberty-mutuals-limu-emu-leads-the-pack-in-insurance-mascot-performance-marketcast-finds\" target=\"_blank\" rel=\"noopener\">MarketCast</a> measured insurance mascots from January 2024 to February 2025, reported by MarTech Edge on 1 April 2025. The beer figure is from an Insurity survey, 7 March 2024, where Mayhem came second to Jake from State Farm. Both rank Mayhem against other insurers' mascots, not against Allstate's own commercials."
  },
  "checkFirst": {
    "id": "check-first",
    "name": "Check First, Swim Meet",
    "officialChannel": true,
    "video": {
      "id": "I6QksAqf0jk",
      "label": "Allstate Check First, Swim Meet",
      "caption": "Check First: Swim Meet &middot; Allstate"
    },
    "scale": "Commercial · A different cast in each spot we checked",
    "title": "Swim Meet, one of the Check First spots",
    "spec": [
      [
        "What it is",
        "A commercial for Allstate car insurance."
      ],
      [
        "The cast",
        "Different people in each of the Check First spots we checked: Swim Meet, Superstitious and Outfit. Each spot is published as a 30-second film and a 15-second cut with the same cast."
      ],
      [
        "What repeats",
        "The campaign name, Check First, and the same opening sentence in Allstate's YouTube description of every spot we checked: \"Checking first is smart.\""
      ]
    ],
    "stats": [
      [
        "New cast",
        "In Each Spot We Checked"
      ],
      [
        "None found",
        "Published Memorability Score"
      ],
      [
        "3 Sep 2026",
        "Published"
      ]
    ],
    "note": "Allstate's own channel, published 3 September 2026. Allstate published the same spot as a 15-second cut on 31 August 2026. We found no published memorability score for this campaign."
  },
  "stratos": {
    "id": "stratos",
    "name": "Stratos, the jump",
    "officialChannel": true,
    "video": {
      "id": "FHtvDA0W34I",
      "label": "Felix Baumgartner's supersonic freefall from 128k', Mission Highlights",
      "caption": "Mission Highlights &middot; Red Bull"
    },
    "scale": "Live event · Streamed on YouTube, then cut into films",
    "title": "A jump from the edge of space",
    "spec": [
      [
        "What it is",
        "A live event on YouTube, then the films cut from it. This highlights film runs 90 seconds."
      ]
    ],
    "stats": [
      [
        "49,048,257",
        "YouTube Views, 14 Sep 2026"
      ],
      [
        "8M+",
        "Live Streams At Once, At The Peak"
      ],
      [
        "Free",
        "No Sign-Up, No Gate"
      ]
    ],
    "note": "<a href=\"https://blog.youtube/news-and-events/mission-complete-red-bull-stratos-lands/\" target=\"_blank\" rel=\"noopener\">YouTube</a> reported more than 8 million concurrent livestreams at the peak, the most of any livestream on YouTube at the time, on its own blog, 14 October 2012. Red Bull's own channel; views read 14 September 2026. Both films in this round sit on Red Bull's own channel."
  },
  "confession": {
    "id": "confession",
    "name": "Confession, the cartoon",
    "officialChannel": true,
    "video": {
      "id": "0b3OPo9wHuk",
      "label": "Confession, a 2011 Red Bull cartoon advert",
      "caption": "Confession, 2011 &middot; Red Bull"
    },
    "scale": "Commercial · Animated, thirty seconds",
    "title": "A thirty-second cartoon commercial",
    "spec": [
      [
        "What it is",
        "An animated commercial in the cartoon style Red Bull has used since 1989."
      ]
    ],
    "stats": [
      [
        "251,604",
        "YouTube Views, 14 Sep 2026"
      ],
      [
        "Since 1989",
        "Red Bull Cartoon Commercials"
      ],
      [
        "26 Jan 2011",
        "Published"
      ]
    ],
    "note": "Red Bull's own channel, published 26 January 2011; views read 14 September 2026. Both films in this round sit on Red Bull's own channel, so the two counts can be compared. Red Bull's first cartoon commercials ran in 1989, according to the <a href=\"https://www.kunstmeile.at/en/program/gives-you-wings\" target=\"_blank\" rel=\"noopener\">Kunstmeile Krems</a> exhibition \"Gives You Wings. 30 Years of Cartoons by Red Bull\", 2017."
  },
  "yetiFilm": {
    "id": "yeti-presents",
    "name": "A Thousand Casts, the YETI Presents film",
    "officialChannel": true,
    "video": {
      "id": "OmrufRLGdAk",
      "label": "YETI Presents, A Thousand Casts",
      "caption": "A Thousand Casts &middot; YETI"
    },
    "scale": "Documentary · A YETI Presents film",
    "title": "A film YETI made",
    "spec": [
      [
        "What it is",
        "A documentary in the YETI Presents series. This one follows a fly fishing trip to Bhutan and runs 28 minutes."
      ]
    ],
    "stats": [
      [
        "1,371,487",
        "YouTube Views, 14 Sep 2026"
      ],
      [
        "Since 2015",
        "YETI Presents Has Run"
      ],
      [
        "YETI",
        "Owns The Channel The Film Sits On"
      ]
    ],
    "note": "YETI's own channel, published 15 August 2023; views read 14 September 2026. The two films in this round sit on different channels, and whose channel each one sits on is the point of the round."
  },
  "pbrSponsor": {
    "id": "pbr-sponsor",
    "name": "YETI's PBR sponsorship",
    "officialChannel": true,
    "video": {
      "id": "6ti-Ky0zYhA",
      "label": "2026 PBR YETI Bucking Bull Champion Ransom",
      "caption": "The 2026 PBR YETI Bucking Bull Champion &middot; PBR"
    },
    "scale": "Sponsorship · Inside PBR's own coverage",
    "title": "A PBR award named after YETI",
    "spec": [
      [
        "What it is",
        "A season award named after YETI, inside coverage that Professional Bull Riders makes. This segment runs seven and a half minutes."
      ]
    ],
    "stats": [
      [
        "13,732",
        "YouTube Views, 14 Sep 2026"
      ],
      [
        "Since 2017",
        "YETI Has Sponsored PBR"
      ],
      [
        "PBR",
        "Owns The Channel The Film Sits On"
      ]
    ],
    "note": "PBR's own channel, published 17 May 2026; views read 14 September 2026. YETI first sponsored PBR in 2013, the deal lapsed, and it resumed in 2017, as reported by Front Office Sports in October 2019."
  }
};

window.ROUNDS = [
  {
    "rung": "repetition",
    "id": "once-or-again",
    "lens": [
      "Consistency Is Key"
    ],
    "sides": [
      "ricos",
      "tideSpot"
    ],
    "winner": "ricos",
    "quote": "\"You need it to be episodic, because a series earns you a return visit and a one off never does.\"",
    "cite": "Tom Langan, Welcome to The Taco Drama, 30 July 2026",
    "url": "https://www.linkedin.com/pulse/welcome-taco-drama-tom-langan-wusce",
    "job": "P&G: one film, or a twenty-two episode series?",
    "measure": "got more views",
    "why": {
      "question": "Both are P&G. Why did the series get more views?",
      "options": [
        {
          "side": "ricos",
          "text": "A series gives people a reason to come back."
        },
        {
          "side": "tideSpot",
          "text": "One film can run everywhere at once, so it reaches more people."
        },
        {
          "side": "tideSpot",
          "text": "One polished film costs far less to make than twenty-two episodes."
        }
      ]
    }
  },
  {
    "rung": "format",
    "id": "line-or-cast",
    "lens": [
      "Consistency Is Key",
      "It's Not About You. It's About Them."
    ],
    "sides": [
      "mayhem",
      "checkFirst"
    ],
    "winner": "mayhem",
    "quote": "MarketCast put Mayhem first among insurance mascots for likeability and for the most memorable ads. A separate Insurity survey of more than 1,000 US adults asked which mascot they would most like to grab a beer with. 31 percent picked Mayhem, second only to Jake from State Farm at 34 percent.",
    "cite": "MarketCast via MarTech Edge, 1 April 2025, and Insurity via Business Wire, 7 March 2024",
    "url": "https://martechedge.com/news/liberty-mutuals-limu-emu-leads-the-pack-in-insurance-mascot-performance-marketcast-finds",
    "job": "Allstate: Mayhem, or a new cast each time?",
    "measure": "do people remember",
    "why": {
      "question": "Allstate makes both. Why do people remember Mayhem?",
      "options": [
        {
          "side": "checkFirst",
          "text": "A fresh cast in every spot keeps a campaign from going stale."
        },
        {
          "side": "mayhem",
          "text": "People have grown fond of Mayhem, so each new spot is a chance to see what situation he is in next."
        },
        {
          "side": "checkFirst",
          "text": "A campaign name that repeats in every spot gives people as much to hold on to as one character does."
        }
      ]
    }
  },
  {
    "rung": "audience",
    "id": "them-or-you",
    "lens": [
      "Give Without Expectation",
      "It's Not About You. It's About Them."
    ],
    "sides": [
      "stratos",
      "confession"
    ],
    "winner": "stratos",
    "quote": "\"They didn't gate it behind a sign-up. They didn't cut away to a guy chugging a can the second Felix landed.\"",
    "cite": "Tom Langan, Where the Rubber Meets The Restaurant, 10 June 2026",
    "url": "https://www.linkedin.com/pulse/where-rubber-meets-restaurant-tom-langan-gllme",
    "job": "Red Bull: a jump from the edge of space, or a thirty-second cartoon?",
    "measure": "was watched more",
    "why": {
      "question": "Both films are Red Bull, on the same channel. Why did the jump get nearly two hundred times the views?",
      "options": [
        {
          "side": "stratos",
          "text": "The jump was something people wanted to watch for its own sake, and Red Bull gave it away free with nothing asked in return."
        },
        {
          "side": "confession",
          "text": "A thirty-second cartoon costs little enough to run all year."
        },
        {
          "side": "confession",
          "text": "Putting the product on screen is what turns attention into sales."
        }
      ]
    }
  },
  {
    "rung": "ownership",
    "id": "own-or-rent",
    "lens": [
      "Give Without Expectation",
      "It's Not About You. It's About Them."
    ],
    "sides": [
      "yetiFilm",
      "pbrSponsor"
    ],
    "winner": "yetiFilm",
    "quote": "PBR makes the film about its award and owns the channel that film sits on. YETI makes A Thousand Casts and owns the channel that film sits on.",
    "cite": "PBR, 17 May 2026, and YETI, 15 August 2023",
    "url": "https://www.youtube.com/watch?v=6ti-Ky0zYhA",
    "job": "YETI: make the film, or put your name on somebody else's?",
    "measure": "did more for YETI",
    "why": {
      "question": "Both are YETI. Why does the film do more for YETI in the long run?",
      "options": [
        {
          "side": "yetiFilm",
          "text": "The film sits on a channel YETI owns, so the audience the film brings in is YETI's to keep."
        },
        {
          "side": "pbrSponsor",
          "text": "A sponsorship puts the name in front of a crowd that has already gathered."
        },
        {
          "side": "pbrSponsor",
          "text": "Naming an award costs less than producing a documentary."
        }
      ]
    }
  }
];

window.COPY = {
  "brand": "Talex Media",
  "eyebrow": "A choose your own adventure case study · draft for Tom",
  "title": "Which one worked?",
  "lead": "Each of the four rounds shows one company two ways. Pick the one that worked, then say why.",
  "gate": "\"If you stripped your name and your product off this piece of content, would anyone still want to watch it?\"",
  "gateCite": "Tom Langan, What's 100 Years Old is New Again, 22 May 2026",
  "gateUrl": "https://www.linkedin.com/pulse/whats-100-years-old-new-again-tom-langan-6bm2e",
  "start": "Start round one",
  "roundLabel": "Round {n} of {total}",
  "pickStep": "Pick",
  "pickLead": "Which one {measure}?",
  "pickInstruction": "Choose the one you think worked.",
  "lock": "Lock in my pick",
  "revealStep": "What worked",
  "calledWinner": "You called it.",
  "missedWinner": "You picked {pick}. The one that worked was {winner}.",
  "youSaidRight": "Your pick. Right.",
  "youSaidWrong": "Your pick",
  "realOrder": "What worked",
  "cmpYou": "You said",
  "cmpReal": "Real",
  "whyStep": "Why did it work?",
  "whyLead": "The one that worked is {winner}.",
  "choose": "Lock in my answer",
  "whyRight": "Right.",
  "whyWrong": "Not this one.",
  "whyRevealStep": "The reason",
  "optionTrueOf": "About {name}",
  "winnerFact": "Why it worked",
  "yourAnswer": "Your answer",
  "sourceLabel": "The source",
  "nextRound": "Round {n}",
  "seeResult": "See my result",
  "resultStep": "Your result",
  "resultHeading": "You called {n} of 8.",
  "resultHigh": "You read these the way we do.",
  "resultLow": "Your instinct and the examples disagreed.",
  "highFrom": 6,
  "scoreLabel": "Points",
  "streakLabel": "Streak",
  "plusOne": "+1",
  "medalNames": [
    "Gold",
    "Silver"
  ],
  "tiers": [
    {
      "from": 8,
      "name": "Perfect read"
    },
    {
      "from": 6,
      "name": "Close read"
    },
    {
      "from": 0,
      "name": "First look"
    }
  ],
  "logRight": "called it",
  "logMissed": "missed it",
  "reasonRow": "Reason",
  "recordPick": "Pick",
  "synthesisHeading": "Put the four rounds together",
  "synthesis": [
    "A series gives people a reason to come back. A single film does not.",
    "Coming back is not enough on its own, and a line that repeats is not the same as a cast that returns. People grow fond of a cast and come back to see what situation those people are in next. A new cast every time, however familiar the line, gives an audience nobody to grow fond of.",
    "People return for something they want to watch, not for something about the product.",
    "When you own the show, the audience is yours, not rented."
  ],
  "synthesisClose": "Could your company make a show that comes back every week or every month, with a format and a cast your audience gets to know? Could you make that show for your audience rather than about your company, and own it rather than rent space in somebody else's show?",
  "cta": {
    "heading": "Do you have the team to make it?",
    "copy": "If you have the idea but not the team to make it, Talex is the team.",
    "button": "Book A Call With Our Team",
    "url": "https://calendly.com/talextom/20-min-discovery-call"
  },
  "share": "Send this to a colleague",
  "shared": "Link copied",
  "startOver": "Start over",
  "sample": "Every film plays on the page, and each card names where its figures came from. Draft: the why-answers are not yet approved by Tom.",
  "ordinals": [
    "first",
    "second"
  ]
};
