// Writes every word a viewer sees, in the order they see it, to copy-deck.md.
// The Talex linter reads HTML, Markdown and plain text, but this page keeps its words in
// content.js, so linting the page directly would miss them. Run:  node extract-copy.js
const fs = require('fs');
const path = require('path');
const w = {};
new Function('window', fs.readFileSync(path.join(__dirname, 'content.js'), 'utf8'))(w);
const { SIDES: S, ROUNDS: R, COPY: C } = w;

// Strip markup so the linter judges the prose, not the tags. Keep link text.
const plain = (t) => String(t == null ? '' : t)
  .replace(/<a [^>]*>([^<]*)<\/a>/g, '$1')
  .replace(/<[^>]+>/g, '')
  .replace(/&middot;/g, '·').replace(/&amp;/g, '&').replace(/&rsquo;/g, '’');

const out = [];
const h = (t) => out.push('', '## ' + t, '');
const p = (label, t) => { if (t) out.push('**' + label + ':** ' + plain(t)); };

out.push('# Which one worked? One company, two ways', '',
  'Every reader-visible string on https://talexmedia.github.io/lead-magnet-legendeering-ladder/',
  'extracted from content.js in page order. Generated by extract-copy.js. Do not edit by hand.');

h('Landing screen');
p('Eyebrow', C.eyebrow); p('Title', C.title); p('Lead', C.lead);
p('Gate quote', C.gate); p('Gate credit', C.gateCite);
p('Notice', C.sample); p('Start button', C.start);

R.forEach((r, i) => {
  h('Round ' + (i + 1) + ' of ' + R.length + ', the ' + r.rung + ' rung');
  p('Headline', r.job);
  p('Question under it', C.pickLead.replace('{measure}', r.measure));
  p('Tags', r.lens.join(' / '));
  p('Instruction', C.pickInstruction);
  r.sides.forEach((k) => {
    const s = S[k];
    out.push('', '### Card: ' + plain(s.name) + (k === r.winner ? ' (the side that worked)' : ''), '');
    p('Film caption', s.video && s.video.caption);
    p('Category line', s.scale); p('Card title', s.title);
    s.spec.forEach((row) => p(row[0], row[1]));
    out.push('**Stats, shown after the pick:** ' + s.stats.map((x) => plain(x[0]) + ' ' + plain(x[1])).join(' | '));
    p('Source note, shown after the pick', s.note);
    if (s.fromLibrary) out.push('_This card is copied word for word from the approved block library and is locked._');
  });
  out.push('');
  p('Why question', r.why.question);
  r.why.options.forEach((o, j) => out.push('- Option ' + String.fromCharCode(65 + j) + (o.side === r.winner ? ' (correct)' : '') + ': ' + plain(o.text)));
  out.push('');
  p('Source quote', r.quote); p('Source credit', r.cite); p('What it teaches', r.teach);
});

h('Result screen');
p('Heading', C.resultHeading); p('Subheading', C.resultSub);
p('If they scored high', C.resultHigh); p('If they scored low', C.resultLow);
p('Synthesis heading', C.synthesisHeading);
(C.synthesis || []).forEach((l, i) => out.push((i + 1) + '. ' + plain(l)));
out.push('');
p('Closing question', C.synthesisClose);
p('Call to action heading', C.cta.heading); p('Call to action copy', C.cta.copy); p('Call to action button', C.cta.button);

h('Interface labels');
['lock', 'calledWinner', 'missedWinner', 'whyStep', 'whyLead', 'choose', 'whyRight', 'whyWrong', 'takeawayLabel', 'sourceLabel', 'approval', 'seeResult', 'share', 'print', 'startOver']
  .forEach((k) => p(k, C[k]));

fs.writeFileSync(path.join(__dirname, 'copy-deck.md'), out.join('\n') + '\n', 'utf8');
console.log('copy-deck.md written, ' + out.length + ' lines');
